# source: https://github.com/manucabral/pybrinf/blob/main/pybrinf/browsers.py

BROWSERS = [
    {
        "name": "Chrome",
        "fullname": "Google Chrome",
        "process": {"win32": "chrome.exe", "linux": "google-chrome"},
        "profilePath": "\\AppData\\Local\\Google\\Chrome\\User Data\\",
        "progid": "ChromeHTML",
        "chromium": True,
    },
    {
        "name": "Yandex",
        "fullname": "Yandex Browser",
        "process": {"win32": "browser.exe", "linux": "yandex-browser"},
        "profilePath": "\\AppData\\Local\\Yandex\\YandexBrowser\\User Data\\",
        "chromium": True,
        "progid": "YandexHTML",
    },
    {
        "name": "Edge",
        "fullname": "Microsoft Edge",
        "process": {"win32": "msedge.exe", "linux": "sure??"},
        "profilePath": "\\AppData\\Local\\Microsoft\\Edge\\User Data\\",
        "progid": "EdgeHTML",
        "chromium": True,
    },
    {
        "name": "Opera",
        "fullname": "Opera",
        "process": {"win32": "opera.exe", "linux": "..."},
        "profilePath": "\\AppData\\Roaming\\Opera Software\\Opera Stable\\",
        "progid": "OperaHTML",
        "chromium": True,
    },
    {
        "name": "Opera GXStable",
        "fullname": "Opera GX",
        "process": {"win32": "opera.exe", "linux": "..."},
        "profilePath": "\\AppData\\Roaming\\Opera Software\\Opera GX Stable\\",
        "progid": "OperaGXHTML",
        "chromium": True,
    },
    {
        "name": "OperaDev",
        "fullname": "Opera Developer (Opera One)",
        "process": {"win32": "opera.exe", "linux": "..."},
        "profilePath": "\\AppData\\Roaming\\Opera Software\\Opera Dev\\",
        "progid": "Operadeveloper",
        "chromium": True,
    },
    {
        "name": "Vivaldi",
        "fullname": "Vivaldi Browser",
        "process": {"win32": "vivaldi.exe", "linux": "..."},
        "profilePath": "\\AppData\\Local\\Vivaldi\\User Data\\",
        "progid": "VivaldiHTML",
        "chromium": True,
    },
    {
        "name": "Brave",
        "fullname": "Brave Browser",
        "process": {"win32": "brave.exe", "linux": "..."},
        "profilePath": "\\AppData\\Local\\BraveSoftware\\Brave-browser\\User Data\\",
        "progid": "BraveHTML",
        "chromium": True,
    },
]
